apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-topic-creation
spec:
  template:
    spec:
      containers:
      - name: kafka-topic-creator
        image: confluentinc/cp-kafka:latest
        command: ["sh", "-c", "kafka-topics --create --topic udac_counter --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1"]
      restartPolicy: OnFailure
